name: ci-cd

on: [push, pull_request, workflow_dispatch]

jobs:
  test-build:
    permissions:
      contents: read
      packages: read
      id-token: write
    uses: CBIIT/bento-workflows/.github/workflows/test-build.yml@v3.1.1
    with:
      workdir: ./python
      versions: |
        ["3.10","3.11","3.12","3.13"]
      no-test-mdb: true
    secrets: inherit
