name: Who Validates the Validator?
on:
  push:
    branches:
      - fix-actions
  pull_request:
    branches:
      - master

jobs:
  test-validator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Test Validator
        run: |
          pushd validators/mdf-validate
          pip install tox
          tox
          popd
          