name: Who Validates the Validator?
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test-validator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Test Validator
        run: |
          pushd drivers/python
          pip install tox
          pip install "bento-meta@git+https://github.com/CBIIT/bento-meta.git#egg=subdir&subdirectory=python"
          tox --sitepackages
          popd
          
